version: '3'
services:
  front:
    build: 
      context: .
      target: ${BUILD_TARGET}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${PORT_MAPPING}"
    environment:
      - NODE_ENV=${NODE_ENV}